### ISSUE TITLE
🛑 Sistemas de Chamados is down

### ISSUE THREAD

**Issue by tiagojulianoferreira** [ifrs-sertao/status#39]
In [`1d4bfc9`](https://github.com/ifrs-sertao/status/commit/1d4bfc908cf46b03797842df9f9f5368f75e627c
), Sistemas de Chamados (https://suporte.sertao.ifrs.edu.br) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by empereira** [comment]
online again
